// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AppAdminOperationLogPublic
 */
export type AppAdminOperationLogPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Admin User Id
     */
    admin_user_id?: string | null;
    /**
     * Admin Email
     */
    admin_email: string;
    /**
     * Action
     */
    action: string;
    /**
     * Target Type
     */
    target_type: string;
    /**
     * Target Id
     */
    target_id?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AppAdminOperationLogsPublic
 */
export type AppAdminOperationLogsPublic = {
    /**
     * Data
     */
    data: Array<AppAdminOperationLogPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppConfigCreate
 */
export type AppConfigCreate = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
};

/**
 * AppConfigPublic
 */
export type AppConfigPublic = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * AppConfigUpdate
 */
export type AppConfigUpdate = {
    /**
     * Key
     */
    key?: string | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean | null;
};

/**
 * AppConfigValuesPublic
 */
export type AppConfigValuesPublic = {
    /**
     * Data
     */
    data: {
        [key: string]: string;
    };
    /**
     * Count
     */
    count: number;
};

/**
 * AppConfigsPublic
 */
export type AppConfigsPublic = {
    /**
     * Data
     */
    data: Array<AppConfigPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppContentAdminPublic
 */
export type AppContentAdminPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * App User Id
     */
    app_user_id: string;
    author: AppContentAuthorPublic;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Images
     */
    images: Array<AppContentImagePublic>;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
};

/**
 * AppContentAuthorPublic
 */
export type AppContentAuthorPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * AppContentCreate
 */
export type AppContentCreate = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * Image Urls
     */
    image_urls?: Array<string>;
};

/**
 * AppContentImagePublic
 */
export type AppContentImagePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * AppContentPublic
 */
export type AppContentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * App User Id
     */
    app_user_id: string;
    author: AppContentAuthorPublic;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Images
     */
    images: Array<AppContentImagePublic>;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AppContentsAdminPublic
 */
export type AppContentsAdminPublic = {
    /**
     * Data
     */
    data: Array<AppContentAdminPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppContentsPublic
 */
export type AppContentsPublic = {
    /**
     * Data
     */
    data: Array<AppContentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppDeviceLoginRequest
 */
export type AppDeviceLoginRequest = {
    /**
     * Device Uuid
     */
    device_uuid: string;
    /**
     * Platform
     */
    platform: 'ios' | 'android';
};

/**
 * AppDeviceLoginResponse
 */
export type AppDeviceLoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    app_user: AppUserPublic;
    /**
     * Is New User
     */
    is_new_user: boolean;
};

/**
 * AppGenerationCreate
 */
export type AppGenerationCreate = {
    /**
     * Kind
     */
    kind: 'video' | 'image';
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Style
     */
    style?: string;
    /**
     * Aspect Ratio
     */
    aspect_ratio?: string;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Consistency
     */
    consistency?: boolean;
    /**
     * Reference Image Url
     */
    reference_image_url?: string | null;
    /**
     * Character Image Url
     */
    character_image_url?: string | null;
};

/**
 * AppGenerationPublic
 */
export type AppGenerationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * App User Id
     */
    app_user_id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Model
     */
    model: string;
    /**
     * Status
     */
    status: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Style
     */
    style: string;
    /**
     * Aspect Ratio
     */
    aspect_ratio: string;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Consistency
     */
    consistency: boolean;
    /**
     * Reference Image Url
     */
    reference_image_url?: string | null;
    /**
     * Character Image Url
     */
    character_image_url?: string | null;
    /**
     * Output Url
     */
    output_url?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
};

/**
 * AppGenerationQuotaPublic
 */
export type AppGenerationQuotaPublic = {
    /**
     * Video Total
     */
    video_total: number;
    /**
     * Video Used
     */
    video_used: number;
    /**
     * Video Remaining
     */
    video_remaining: number;
    /**
     * Image Total
     */
    image_total: number;
    /**
     * Image Used
     */
    image_used: number;
    /**
     * Image Remaining
     */
    image_remaining: number;
};

/**
 * AppGenerationsPublic
 */
export type AppGenerationsPublic = {
    /**
     * Data
     */
    data: Array<AppGenerationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppOrderCreate
 */
export type AppOrderCreate = {
    /**
     * Provider
     */
    provider: 'apple' | 'google';
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Amount
     */
    amount?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
};

/**
 * AppOrderEventPublic
 */
export type AppOrderEventPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Order Id
     */
    order_id?: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Transaction Id
     */
    transaction_id?: string | null;
    /**
     * Raw Payload
     */
    raw_payload: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AppOrderEventsPublic
 */
export type AppOrderEventsPublic = {
    /**
     * Data
     */
    data: Array<AppOrderEventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppOrderPublic
 */
export type AppOrderPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * App User Id
     */
    app_user_id: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Amount
     */
    amount?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Transaction Id
     */
    transaction_id?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Paid At
     */
    paid_at?: string | null;
};

/**
 * AppOrdersPublic
 */
export type AppOrdersPublic = {
    /**
     * Data
     */
    data: Array<AppOrderPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AppUploadPublic
 */
export type AppUploadPublic = {
    /**
     * Url
     */
    url: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
};

/**
 * AppUserAdminPublic
 */
export type AppUserAdminPublic = {
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Status
     */
    status?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
};

/**
 * AppUserProfileUpdate
 */
export type AppUserProfileUpdate = {
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * AppUserPublic
 */
export type AppUserPublic = {
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Status
     */
    status?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AppUserStatusUpdate
 */
export type AppUserStatusUpdate = {
    /**
     * Status
     */
    status: 'active' | 'disabled';
};

/**
 * AppUsersPublic
 */
export type AppUsersPublic = {
    /**
     * Data
     */
    data: Array<AppUserAdminPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_app uploads-upload_app_image
 */
export type Body_app_uploads_upload_app_image = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PaymentCallbackRequest
 */
export type PaymentCallbackRequest = {
    /**
     * Order Id
     */
    order_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Status
     */
    status: 'paid' | 'failed' | 'refunded' | 'canceled';
    /**
     * Transaction Id
     */
    transaction_id?: string | null;
    /**
     * Raw Data
     */
    raw_data?: {
        [key: string]: unknown;
    };
};

/**
 * PaymentCallbackResponse
 */
export type PaymentCallbackResponse = {
    order?: AppOrderPublic | null;
    event: AppOrderEventPublic;
    /**
     * Is Duplicate
     */
    is_duplicate: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type appAuthDeviceLoginData = {
    body: AppDeviceLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/app/auth/device-login';
};

export type appAuthDeviceLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appAuthDeviceLoginError = appAuthDeviceLoginErrors[keyof appAuthDeviceLoginErrors];

export type appAuthDeviceLoginResponses = {
    /**
     * Successful Response
     */
    200: AppDeviceLoginResponse;
};

export type appAuthDeviceLoginResponse = appAuthDeviceLoginResponses[keyof appAuthDeviceLoginResponses];

export type appAuthTestAppTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/app/auth/test-token';
};

export type appAuthTestAppTokenResponses = {
    /**
     * Successful Response
     */
    200: AppUserPublic;
};

export type appAuthTestAppTokenResponse = appAuthTestAppTokenResponses[keyof appAuthTestAppTokenResponses];

export type appUsersReadAppUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/app/users/me';
};

export type appUsersReadAppUserMeResponses = {
    /**
     * Successful Response
     */
    200: AppUserPublic;
};

export type appUsersReadAppUserMeResponse = appUsersReadAppUserMeResponses[keyof appUsersReadAppUserMeResponses];

export type appUsersUpdateAppUserMeData = {
    body: AppUserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/app/users/me';
};

export type appUsersUpdateAppUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appUsersUpdateAppUserMeError = appUsersUpdateAppUserMeErrors[keyof appUsersUpdateAppUserMeErrors];

export type appUsersUpdateAppUserMeResponses = {
    /**
     * Successful Response
     */
    200: AppUserPublic;
};

export type appUsersUpdateAppUserMeResponse = appUsersUpdateAppUserMeResponses[keyof appUsersUpdateAppUserMeResponses];

export type appUploadsUploadAppImageData = {
    body: Body_app_uploads_upload_app_image;
    path?: never;
    query?: never;
    url: '/api/v1/app/uploads/images';
};

export type appUploadsUploadAppImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appUploadsUploadAppImageError = appUploadsUploadAppImageErrors[keyof appUploadsUploadAppImageErrors];

export type appUploadsUploadAppImageResponses = {
    /**
     * Successful Response
     */
    200: AppUploadPublic;
};

export type appUploadsUploadAppImageResponse = appUploadsUploadAppImageResponses[keyof appUploadsUploadAppImageResponses];

export type appContentsCreateContentData = {
    body: AppContentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/app/contents/';
};

export type appContentsCreateContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appContentsCreateContentError = appContentsCreateContentErrors[keyof appContentsCreateContentErrors];

export type appContentsCreateContentResponses = {
    /**
     * Successful Response
     */
    200: AppContentPublic;
};

export type appContentsCreateContentResponse = appContentsCreateContentResponses[keyof appContentsCreateContentResponses];

export type appContentsReadContentFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/app/contents/feed';
};

export type appContentsReadContentFeedErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appContentsReadContentFeedError = appContentsReadContentFeedErrors[keyof appContentsReadContentFeedErrors];

export type appContentsReadContentFeedResponses = {
    /**
     * Successful Response
     */
    200: AppContentsPublic;
};

export type appContentsReadContentFeedResponse = appContentsReadContentFeedResponses[keyof appContentsReadContentFeedResponses];

export type appContentsReadContentData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query?: never;
    url: '/api/v1/app/contents/{content_id}';
};

export type appContentsReadContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appContentsReadContentError = appContentsReadContentErrors[keyof appContentsReadContentErrors];

export type appContentsReadContentResponses = {
    /**
     * Successful Response
     */
    200: AppContentPublic;
};

export type appContentsReadContentResponse = appContentsReadContentResponses[keyof appContentsReadContentResponses];

export type appGenerationsReadGenerationQuotaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/app/generations/quota';
};

export type appGenerationsReadGenerationQuotaResponses = {
    /**
     * Successful Response
     */
    200: AppGenerationQuotaPublic;
};

export type appGenerationsReadGenerationQuotaResponse = appGenerationsReadGenerationQuotaResponses[keyof appGenerationsReadGenerationQuotaResponses];

export type appGenerationsReadGenerationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Kind
         */
        kind?: 'video' | 'image' | null;
    };
    url: '/api/v1/app/generations/';
};

export type appGenerationsReadGenerationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appGenerationsReadGenerationsError = appGenerationsReadGenerationsErrors[keyof appGenerationsReadGenerationsErrors];

export type appGenerationsReadGenerationsResponses = {
    /**
     * Successful Response
     */
    200: AppGenerationsPublic;
};

export type appGenerationsReadGenerationsResponse = appGenerationsReadGenerationsResponses[keyof appGenerationsReadGenerationsResponses];

export type appGenerationsCreateGenerationData = {
    body: AppGenerationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/app/generations/';
};

export type appGenerationsCreateGenerationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appGenerationsCreateGenerationError = appGenerationsCreateGenerationErrors[keyof appGenerationsCreateGenerationErrors];

export type appGenerationsCreateGenerationResponses = {
    /**
     * Successful Response
     */
    200: AppGenerationPublic;
};

export type appGenerationsCreateGenerationResponse = appGenerationsCreateGenerationResponses[keyof appGenerationsCreateGenerationResponses];

export type appGenerationsDeleteGenerationData = {
    body?: never;
    path: {
        /**
         * Generation Id
         */
        generation_id: string;
    };
    query?: never;
    url: '/api/v1/app/generations/{generation_id}';
};

export type appGenerationsDeleteGenerationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appGenerationsDeleteGenerationError = appGenerationsDeleteGenerationErrors[keyof appGenerationsDeleteGenerationErrors];

export type appGenerationsDeleteGenerationResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type appGenerationsDeleteGenerationResponse = appGenerationsDeleteGenerationResponses[keyof appGenerationsDeleteGenerationResponses];

export type appGenerationsReadGenerationData = {
    body?: never;
    path: {
        /**
         * Generation Id
         */
        generation_id: string;
    };
    query?: never;
    url: '/api/v1/app/generations/{generation_id}';
};

export type appGenerationsReadGenerationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appGenerationsReadGenerationError = appGenerationsReadGenerationErrors[keyof appGenerationsReadGenerationErrors];

export type appGenerationsReadGenerationResponses = {
    /**
     * Successful Response
     */
    200: AppGenerationPublic;
};

export type appGenerationsReadGenerationResponse = appGenerationsReadGenerationResponses[keyof appGenerationsReadGenerationResponses];

export type appConfigsReadAppConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/app/configs';
};

export type appConfigsReadAppConfigsResponses = {
    /**
     * Successful Response
     */
    200: AppConfigValuesPublic;
};

export type appConfigsReadAppConfigsResponse = appConfigsReadAppConfigsResponses[keyof appConfigsReadAppConfigsResponses];

export type appOrdersReadOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/app/orders';
};

export type appOrdersReadOrdersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appOrdersReadOrdersError = appOrdersReadOrdersErrors[keyof appOrdersReadOrdersErrors];

export type appOrdersReadOrdersResponses = {
    /**
     * Successful Response
     */
    200: AppOrdersPublic;
};

export type appOrdersReadOrdersResponse = appOrdersReadOrdersResponses[keyof appOrdersReadOrdersResponses];

export type appOrdersCreateOrderData = {
    body: AppOrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/app/orders';
};

export type appOrdersCreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appOrdersCreateOrderError = appOrdersCreateOrderErrors[keyof appOrdersCreateOrderErrors];

export type appOrdersCreateOrderResponses = {
    /**
     * Successful Response
     */
    200: AppOrderPublic;
};

export type appOrdersCreateOrderResponse = appOrdersCreateOrderResponses[keyof appOrdersCreateOrderResponses];

export type appOrdersReadOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/app/orders/{order_id}';
};

export type appOrdersReadOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appOrdersReadOrderError = appOrdersReadOrderErrors[keyof appOrdersReadOrderErrors];

export type appOrdersReadOrderResponses = {
    /**
     * Successful Response
     */
    200: AppOrderPublic;
};

export type appOrdersReadOrderResponse = appOrdersReadOrderResponses[keyof appOrdersReadOrderResponses];

export type adminAppReadAppUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: 'active' | 'disabled' | 'deleted' | null;
    };
    url: '/api/v1/admin/app/users';
};

export type adminAppReadAppUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppUsersError = adminAppReadAppUsersErrors[keyof adminAppReadAppUsersErrors];

export type adminAppReadAppUsersResponses = {
    /**
     * Successful Response
     */
    200: AppUsersPublic;
};

export type adminAppReadAppUsersResponse = adminAppReadAppUsersResponses[keyof adminAppReadAppUsersResponses];

export type adminAppUpdateAppUserStatusData = {
    body: AppUserStatusUpdate;
    path: {
        /**
         * App User Id
         */
        app_user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/users/{app_user_id}/status';
};

export type adminAppUpdateAppUserStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppUpdateAppUserStatusError = adminAppUpdateAppUserStatusErrors[keyof adminAppUpdateAppUserStatusErrors];

export type adminAppUpdateAppUserStatusResponses = {
    /**
     * Successful Response
     */
    200: AppUserAdminPublic;
};

export type adminAppUpdateAppUserStatusResponse = adminAppUpdateAppUserStatusResponses[keyof adminAppUpdateAppUserStatusResponses];

export type adminAppDeleteAppUserData = {
    body?: never;
    path: {
        /**
         * App User Id
         */
        app_user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/users/{app_user_id}';
};

export type adminAppDeleteAppUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppDeleteAppUserError = adminAppDeleteAppUserErrors[keyof adminAppDeleteAppUserErrors];

export type adminAppDeleteAppUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminAppDeleteAppUserResponse = adminAppDeleteAppUserResponses[keyof adminAppDeleteAppUserResponses];

export type adminAppReadAppContentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: 'active' | 'deleted' | null;
    };
    url: '/api/v1/admin/app/contents';
};

export type adminAppReadAppContentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppContentsError = adminAppReadAppContentsErrors[keyof adminAppReadAppContentsErrors];

export type adminAppReadAppContentsResponses = {
    /**
     * Successful Response
     */
    200: AppContentsAdminPublic;
};

export type adminAppReadAppContentsResponse = adminAppReadAppContentsResponses[keyof adminAppReadAppContentsResponses];

export type adminAppDeleteAppContentData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/contents/{content_id}';
};

export type adminAppDeleteAppContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppDeleteAppContentError = adminAppDeleteAppContentErrors[keyof adminAppDeleteAppContentErrors];

export type adminAppDeleteAppContentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminAppDeleteAppContentResponse = adminAppDeleteAppContentResponses[keyof adminAppDeleteAppContentResponses];

export type adminAppReadAppOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: 'created' | 'paid' | 'failed' | 'refunded' | 'canceled' | null;
        /**
         * Provider
         */
        provider?: 'apple' | 'google' | null;
    };
    url: '/api/v1/admin/app/orders';
};

export type adminAppReadAppOrdersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppOrdersError = adminAppReadAppOrdersErrors[keyof adminAppReadAppOrdersErrors];

export type adminAppReadAppOrdersResponses = {
    /**
     * Successful Response
     */
    200: AppOrdersPublic;
};

export type adminAppReadAppOrdersResponse = adminAppReadAppOrdersResponses[keyof adminAppReadAppOrdersResponses];

export type adminAppReadAppOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/orders/{order_id}';
};

export type adminAppReadAppOrderErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppOrderError = adminAppReadAppOrderErrors[keyof adminAppReadAppOrderErrors];

export type adminAppReadAppOrderResponses = {
    /**
     * Successful Response
     */
    200: AppOrderPublic;
};

export type adminAppReadAppOrderResponse = adminAppReadAppOrderResponses[keyof adminAppReadAppOrderResponses];

export type adminAppReadAppOrderEventsData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/orders/{order_id}/events';
};

export type adminAppReadAppOrderEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppOrderEventsError = adminAppReadAppOrderEventsErrors[keyof adminAppReadAppOrderEventsErrors];

export type adminAppReadAppOrderEventsResponses = {
    /**
     * Successful Response
     */
    200: AppOrderEventsPublic;
};

export type adminAppReadAppOrderEventsResponse = adminAppReadAppOrderEventsResponses[keyof adminAppReadAppOrderEventsResponses];

export type adminAppReadAppAdminOperationLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Action
         */
        action?: string | null;
        /**
         * Target Type
         */
        target_type?: string | null;
    };
    url: '/api/v1/admin/app/operation-logs';
};

export type adminAppReadAppAdminOperationLogsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppAdminOperationLogsError = adminAppReadAppAdminOperationLogsErrors[keyof adminAppReadAppAdminOperationLogsErrors];

export type adminAppReadAppAdminOperationLogsResponses = {
    /**
     * Successful Response
     */
    200: AppAdminOperationLogsPublic;
};

export type adminAppReadAppAdminOperationLogsResponse = adminAppReadAppAdminOperationLogsResponses[keyof adminAppReadAppAdminOperationLogsResponses];

export type adminAppReadAppConfigsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Is Enabled
         */
        is_enabled?: boolean | null;
    };
    url: '/api/v1/admin/app/configs';
};

export type adminAppReadAppConfigsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppConfigsError = adminAppReadAppConfigsErrors[keyof adminAppReadAppConfigsErrors];

export type adminAppReadAppConfigsResponses = {
    /**
     * Successful Response
     */
    200: AppConfigsPublic;
};

export type adminAppReadAppConfigsResponse = adminAppReadAppConfigsResponses[keyof adminAppReadAppConfigsResponses];

export type adminAppCreateAppConfigData = {
    body: AppConfigCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/app/configs';
};

export type adminAppCreateAppConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppCreateAppConfigError = adminAppCreateAppConfigErrors[keyof adminAppCreateAppConfigErrors];

export type adminAppCreateAppConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfigPublic;
};

export type adminAppCreateAppConfigResponse = adminAppCreateAppConfigResponses[keyof adminAppCreateAppConfigResponses];

export type adminAppReadAppConfigData = {
    body?: never;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/configs/{config_id}';
};

export type adminAppReadAppConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppReadAppConfigError = adminAppReadAppConfigErrors[keyof adminAppReadAppConfigErrors];

export type adminAppReadAppConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfigPublic;
};

export type adminAppReadAppConfigResponse = adminAppReadAppConfigResponses[keyof adminAppReadAppConfigResponses];

export type adminAppUpdateAppConfigData = {
    body: AppConfigUpdate;
    path: {
        /**
         * Config Id
         */
        config_id: string;
    };
    query?: never;
    url: '/api/v1/admin/app/configs/{config_id}';
};

export type adminAppUpdateAppConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAppUpdateAppConfigError = adminAppUpdateAppConfigErrors[keyof adminAppUpdateAppConfigErrors];

export type adminAppUpdateAppConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfigPublic;
};

export type adminAppUpdateAppConfigResponse = adminAppUpdateAppConfigResponses[keyof adminAppUpdateAppConfigResponses];

export type paymentWebhooksReceiveAppleIapCallbackData = {
    body: PaymentCallbackRequest;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/payments/apple-iap';
};

export type paymentWebhooksReceiveAppleIapCallbackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type paymentWebhooksReceiveAppleIapCallbackError = paymentWebhooksReceiveAppleIapCallbackErrors[keyof paymentWebhooksReceiveAppleIapCallbackErrors];

export type paymentWebhooksReceiveAppleIapCallbackResponses = {
    /**
     * Successful Response
     */
    200: PaymentCallbackResponse;
};

export type paymentWebhooksReceiveAppleIapCallbackResponse = paymentWebhooksReceiveAppleIapCallbackResponses[keyof paymentWebhooksReceiveAppleIapCallbackResponses];

export type paymentWebhooksReceiveGooglePlayCallbackData = {
    body: PaymentCallbackRequest;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/payments/google-play';
};

export type paymentWebhooksReceiveGooglePlayCallbackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type paymentWebhooksReceiveGooglePlayCallbackError = paymentWebhooksReceiveGooglePlayCallbackErrors[keyof paymentWebhooksReceiveGooglePlayCallbackErrors];

export type paymentWebhooksReceiveGooglePlayCallbackResponses = {
    /**
     * Successful Response
     */
    200: PaymentCallbackResponse;
};

export type paymentWebhooksReceiveGooglePlayCallbackResponse = paymentWebhooksReceiveGooglePlayCallbackResponses[keyof paymentWebhooksReceiveGooglePlayCallbackResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
